### ISSUE TITLE
line 382 syntax error

### ISSUE THREAD

**Issue by daveruckley** [henroFall/oscar2#4]
When running install_oscar.sh on a pi I get the following error:

./install_oscar.sh: line 382: syntax error near unexpected token `}'
.install_oscar.sh: line 382: `}'

**Comment by henroFall** [comment]
Fixed, thanks for catching this. I really should have worked in the dev branch for this.

I'm doing all of my testing now but it looks like the script is going to execute now. I checked in the wrong one.
